Docker + poprawki
akai-org/blog pull request #21
Opened 2021-04-12 17:10 UTC by Szczepaniak-M

- Edycja postu o Dokerze
- #18 Tłumaczenia
- Naprawa testów

2021-04-12 21:02 UTC, marcinlawnik commented
Looks good to me.

2021-04-12 21:03 UTC, marcinlawnik approved these changes

2021-04-13 08:00 UTC, roertbb requested changes
can look at it && help with that on Wednesday

2021-04-13 08:00 UTC, roertbb commented on src/components/Feed/Feed.js
> +          <time className={styles['feed__item-meta-time']} dateTime={moment(edge.node.frontmatter.date).locale('pl').format('MMMM D, YYYY')}>
I'd rather set `locale` for `moment` globally, rather than adding `locale('pl').` every time we want to format the data

2021-04-13 08:45 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +- Aby wylistować *wszystkie* kontenery używamy komendy: `docker ps -a`. Jest to lista wszystkich kontenerów jakie zostały
```suggestion
- Aby wylistować *wszystkie* kontenery używamy komendy: `docker ps -a`. Jest to lista wszystkich kontenerów, jakie zostały 
```

2021-04-13 08:46 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +przez polecenie `docker ps`. Pojawiają się one w pierwszej i ostatniej kolumnie. Nazwę możemy też nadać sami o czym więcej
```suggestion
przez polecenie `docker ps`. Pojawiają się one w pierwszej i ostatniej kolumnie. Nazwę możemy też nadać sami, o czym więcej 
```

2021-04-13 08:46 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +i wszystkich zmian które zostały w nim dokonane (z wyjątkiem edycji wolumenów, o czym więcej za chwilę)
```suggestion
i wszystkich zmian, które zostały w nim dokonane (z wyjątkiem edycji wolumenów, o czym więcej za chwilę)
```

2021-04-13 08:47 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +tradycyjnego systemu. MySQL używa podanej zmiennej środowiskowej, aby zasetupować hasło dla roota do bazy danych.
```suggestion
tradycyjnego systemu. MySQL używa podanej zmiennej środowiskowej, aby ustawić hasło dla roota do bazy danych. 
```

2021-04-13 08:48 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +* [Docker. Projektowanie i wdrażanie aplikacji, Jaroslaw Krochmalski](https://helion.pl/ksiazki/docker-projektowanie-i-wdrazanie-aplikacji-jaroslaw-krochmalski,docpro.htm#format/d)
```suggestion
* [Docker. Projektowanie i wdrażanie aplikacji, Jarosław Krochmalski](https://helion.pl/ksiazki/docker-projektowanie-i-wdrazanie-aplikacji-jaroslaw-krochmalski,docpro.htm#format/d)
```

2021-04-13 08:52 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +pozwalające na zobaczenie działania Dockera w praktyce. W tym wpisie skupię się na uruchamianiu kontenerów oraz opcjach,
```suggestion
pozwalające zobaczyć działanie Dockera w praktyce. W tym wpisie skupię się na uruchamianiu kontenerów oraz opcjach,
```

2021-04-13 08:53 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +a następnie wylistujemy wszystkie uruchomione kontenery poleceniem
```suggestion
a następnie wylistujemy wszystkie uruchomione kontenery poleceniem: 
```

2021-04-13 08:57 UTC, tobiaszciesielski commented on content/posts/2021-04-14--Wprowadzenie-do-Dockera-cz2.md
> +W kontenerze pojawia nam się katalog `/notatki` który jest zlinkowany do katalogu `/home/tutorial/notatki` hosta. Zmiany
```suggestion
W kontenerze pojawia nam się katalog `/notatki`, który jest zlinkowany do katalogu `/home/tutorial/notatki` hosta. Zmiany
```

2021-04-13 09:02 UTC, tobiaszciesielski requested changes
I have just marked interpunction  and suggest small fixes. Good article overall.

2021-04-14 06:49 UTC, roertbb commented
added https://github.com/Szczepaniak-M/blog/pull/2
wdyt about such solution?

2021-04-14 08:57 UTC, roertbb approved these changes

2021-04-14 11:41 UTC, tobiaszciesielski approved these changes

2021-04-14 16:37 UTC, merged