Blog post o pułapkach w Javie
akai-org/blog pull request #36
Opened 2022-02-22 23:03 UTC by julialamperska

https://github.com/akai-org/spring-course/issues/6

2022-02-23 19:02 UTC, Szczepaniak-M requested changes

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Pierwszą popularną pułapką jest popularny **boolean**, czy też **Boolean**. Jeżeli przyswoiłeś już podstawy programowania, z pewnością wiesz, że boolean jest typem logicznym
```suggestion
Pierwszą popularną pułapką jest popularny `boolean`, czy też `Boolean`. Jeżeli przyswoiłeś już podstawy programowania, z pewnością wiesz, że boolean jest typem logicznym 
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Wyjątkiem są sytuacje, gdy chcemy skorzystać z metod klasy Boolean.
Przy różnicach warto dodać także fakt, że `Boolean` w praktyce jest trójwartościowy, bo może przyjmować wartości null. Prymitywny `boolean` tego nie może.

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Boolean vs boolean – **Integer** jest obiektem, natomiast **int** typem prymitywnym.
```suggestion
Boolean vs boolean – `Integer` jest obiektem, natomiast `int` typem prymitywnym.
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +różne metody pomagające przechowywać i konwertować dane. Jeżeli chcesz skorzystać z metody takiej jak na przykład parseInt, musisz zadeklarować typ zmiennej Integer. Natomiast,
```suggestion
różne metody pomagające przechowywać i konwertować dane. Jeżeli chcesz skorzystać z metody takiej jak na przykład `parseInt`, musisz zadeklarować typ zmiennej `Integer`. Natomiast, 
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Boolean i boolean, Integer i int nie są jedynymi typami zmiennych, które występują parami. Oto pozostałe prymitywne typy zmiennych oraz ich „odpowiedniki” w obiektach:
```suggestion
`Boolean` i `boolean`,` Integer` i `int` nie są jedynymi typami zmiennych, które występują parami. Oto pozostałe prymitywne typy zmiennych oraz ich „odpowiedniki” w obiektach:
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +
Brakuje informacji o problemach w przypadku porównywania obiektów typu Integer. Chodzi o to co jest zademonstrowane tym testem `integerTest`: https://github.com/akai-org/spring-course/blob/master/java-basics-part-2/src/test/java/pl/org/akai/JavaTrapTest.java

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +**String pool** jest wydzielonym fragmentem pamięci, do którego trafiają obiekty typu String utworzone za pomocą operatora new.
```suggestion
**String pool** jest wydzielonym fragmentem pamięci, do którego trafiają obiekty typu String utworzone za pomocą operatora `new`. 
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Wpływa on korzystanie na zużycie pamięci i przyspiesza porównywanie stringów. Trzeba jednak uważać porównując obiekty typu String, ponieważ łatwo można wpaść w pułapkę.
```suggestion
Wpływa on korzystanie na zużycie pamięci i przyspiesza porównywanie stringów. Trzeba jednak uważać porównując obiekty typu `String`, ponieważ łatwo można wpaść w pułapkę.
```

2022-02-23 19:02 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Jak widać, Stringi test11 oraz test22, które zostały utworzone przez operator new zwracają nieprawidłowy wynik, gdy są porównywane za pomocą operatora `==`. Spowodowane jest
```suggestion
Jak widać, Stringi `test11` oraz `test22`, które zostały utworzone przez operator new zwracają nieprawidłowy wynik, gdy są porównywane za pomocą operatora `==`. Spowodowane jest 
```

2022-02-24 23:22 UTC, julialamperska commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Wyjątkiem są sytuacje, gdy chcemy skorzystać z metod klasy Boolean.
Dodane

2022-02-24 23:22 UTC, julialamperska commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Wyjątkiem są sytuacje, gdy chcemy skorzystać z metod klasy Boolean.
Dodane

2022-02-24 23:23 UTC, julialamperska commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Wyjątkiem są sytuacje, gdy chcemy skorzystać z metod klasy Boolean.
Dodane

2022-02-24 23:25 UTC, julialamperska commented
Zmiany dodane

2022-02-27 11:42 UTC, julialamperska reviewed
Zrobione

2022-02-27 12:05 UTC, Szczepaniak-M requested changes

2022-02-27 12:05 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Różnica w zapisie jest jednak istotna. Boolean jest obiektem, a boolean typem prymitywnym. Największą różnicę pomiędzy nimi znajdziemy w pamięci, które zajmują. Istotną różnicę stanowi fakt, że zmien
```suggestion
Różnica w zapisie jest jednak istotna. `Boolean` jest obiektem, a `boolean` typem prymitywnym. Największą różnicę pomiędzy nimi znajdziemy w pamięci, które zajmują. Istotną różnicę stanowi fakt, że zmienna `Boolean` przyjmuje trzy wartości - oprócz standardowego `true` i `false`, może mieć także wartość `null`. Niemniej jednak, zmienna prymitywna typu `boolean` zajmuje znacznie mniej miejsca niż jakikolwiek obiekt. Jej dokładny rozmiar nie jest zdefiniowany, ponieważ zależy od maszyny wirtualnej, ale możemy z pewnością stwierdzić, że obiekt będzie zajmować wielokrotnie więcej pamięci.
```

2022-02-27 12:05 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Z uwagi na to, że zazwyczaj ze zmiennej logicznej korzystamy w prostych celach, korzystanie z obiektu Boolean zazwyczaj jest niepotrzebnym marnowaniem pamięci. Wyjątkiem są sytuacje, gdy chcemy skorz
```suggestion
Z uwagi na to, że zazwyczaj ze zmiennej logicznej korzystamy w prostych celach, korzystanie z obiektu `Boolean` zazwyczaj jest niepotrzebnym marnowaniem pamięci. Wyjątkiem są sytuacje, gdy chcemy skorzystać z metod klasy `Boolean`.
```

2022-02-27 12:05 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +Kolejną pułapką są nazwy popularnych zmiennych liczbowych. Integer (int) jest typem zmiennej całkowitoliczbowej. Różnica w zapisie jest analogiczna jak w przypadku Boolean vs boolean – `Integer` jest
```suggestion
Kolejną pułapką są nazwy popularnych zmiennych liczbowych. Integer (int) jest typem zmiennej całkowitoliczbowej. Różnica w zapisie jest analogiczna jak w przypadku `Boolean` vs `boolean` – `Integer` jest obiektem, natomiast `int` typem prymitywnym.
```

2022-02-27 12:05 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +W tym przypadku, kwestia wyboru typu zmiennej również opiera się na kompromisie pomiędzy ilością zajmowanej pamięci, a metodami wbudowanymi. Obiekt Integer wyposażony jest w różne metody pomagające p
```suggestion
W tym przypadku, kwestia wyboru typu zmiennej również opiera się na kompromisie pomiędzy ilością zajmowanej pamięci, a metodami wbudowanymi. Obiekt `Integer` wyposażony jest w różne metody pomagające przechowywać i konwertować dane. Jeżeli chcesz skorzystać z metody takiej jak na przykład `parseInt`, musisz zadeklarować typ zmiennej jako `Integer`. Ponadto, jeśli chcesz korzystać z klas generycznych, muszą one korzystać z klas. Dlatego też, gdy, na przykład, tworzymy listę przechowującą wartości całkowitoliczbowe można utworzyć obiekt o typie `List<Integer>`, ale nie można `List<int>`. Natomiast, jeżeli nie będzie to potrzebne, warto pozostać przy prymitywnym typie `int`, który pozwoli zaoszczędzić pamięć oraz pozwoli uniknać problemów z porównaniami.
```

2022-02-27 12:09 UTC, Szczepaniak-M approved these changes, later dismissed

2022-02-28 19:32 UTC, Szczepaniak-M commented
Zedytować date i slug na `springcourse3`

2022-02-28 19:34 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +slug: "/posts/springcourse6/"
Zedytować date i slug przed dodaniem

```suggestion
slug: "/posts/springcourse3/"
```

2022-04-02 20:11 UTC, Szczepaniak-M approved these changes, later dismissed

2022-04-02 20:11 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +date: "2022-02-22"
```suggestion
date: "2022-04-03"
```

2022-04-02 20:11 UTC, Szczepaniak-M commented on content/posts/2022-02-22---Pulapki-w-Javie.md
> +category: "dev-ops"
```suggestion
category: "back-end"
```

2022-04-02 20:12 UTC, Szczepaniak-M approved these changes

2022-04-02 20:15 UTC, merged